### ISSUE TITLE
First research paper progress tracker

### ISSUE THREAD

**Issue by geoffxy** [mitdbg/brad#298]
This will be the "overarching" issue used to track the progress of the first research paper. This will primarily track the writing progress, which indirectly captures the other related tasks (experiments, baselines, implementation).

### Front end pen-to-paper first draft

The goal of the first rough draft is to start putting words on paper to "test out" the planned paper structure, story, and get a feel for the interesting/unclear parts of the paper. The paper will need at least one heavy reorganization and editing pass after this part is complete before it's worth seeking external feedback.

- [x] Abstract
- [x] Introduction
  - [x] Contributions list/description
  - [x] Rest of the section
- [x] Motivation
  - [x] Experiments + description
  - [x] Outline of the "requirements"
- [x] Blueprint planning
- [x] System description (BRAD key ideas)
- [x] Conclusion

### Coherence and clarity pass on the front end

This pass will be a heavy editing pass that reorganizes the information and focuses the front end for clarity + coherence.

- [x] Abstract
- [x] Introduction
- [x] Motivation
- [x] Blueprint planning
- [x] Blueprint planning second reorganization and rewrite pass
- [x] BRAD's blueprint planner overview
- [x] Conclusion

### Details pass
These are the "middle" sections of the paper (plus related work). Most edits to these sections will be for improving clarity and conciseness.

- [x] System details
  - [x] Query routing details (incl. specialized functionality)
  - [x] Blueprint scoring
    - [x] Run time + data accessed
    - [x] Scaling for hardware and load
    - [x] Scaling transactional latency
    - [x] Transition times (table movement)
  - [x] Blueprint search
  - [x] Planning triggers
  - [x] Comparators
- [x] Related work

### Evaluation section

See the [Google document](https://docs.google.com/document/d/1GR5gFgEUUyWcvEAnNrWeF75D-_YdlRQDvZmlI5kQUY8). I'll transfer the details over as we make more progress.

- [x] Overview
- [x] Workload description
- [x] Experimental setup
- [x] Scenarios
  - [x] Scale down
  - [x] Scale up (transactions)
  - [x] Scale up (analytics)
  - [x] Data lake / vector specialized functionality
  - [x] Day long experiment
- [x] Query routing
- [x] Overhead
- [x] Scoring accuracy
- [x] Search
- [x] Decision sensitivity

### Additional updates pass

- [x] Add system details to the intro (requested by Tim)
- [x] Blueprint lifecycle/framework tightening
- [x] Non-goals / operational assumptions clarity/precision
- [x] Updated wait time (system load) models (details section)
- [x] Update the related work
- [x] Tighten up the conclusion
- [x] Shorten the evaluation section
- [x] Shorten the details section (can roll several of the model sections into one)
