### ISSUE TITLE
Experiment tracking issue

### ISSUE THREAD

**Issue by geoffxy** [mitdbg/brad#388]
**Experiment prep**
- [x] Ad-hoc query router
- [x] Generate more ad-hoc query predictions to bootstrap the router
- [x] Analyze the resource/load scaling data - update these models
  - [x] Aurora
  - [x] Redshift 
- [x] Test out the benefit comparator
- [x] Add transaction scale up to the day long experiment
- [x] Update our config management to ensure better reproducibility
- [x] Preparation for the day long experiment
  - [x] Clone the cluster for use in the day long experiment
  - [x] Code up the scripts needed for the day long experiment

**End to end scenarios**
- [x] Vector with previous setup (working alongside others)
- [x] Update existing end-to-end scenario plots (the plotting code)
- [x] Scale down w/ latest and benefit comparator
- [x] Scale up (txn) w/ latest and benefit comparator
- [x] Scale up (analytics) w/ latest and benefit comparator
- [x] Vector w/ latest and benefit comparator
- [x] Day long experiment - set up and run once
- [x] Day long experiment

**End to end baselines**
- [x] Scale down
- [x] Scale up (txns)
- [x] Scale up (analytics)
- [x] Vector
- [x] Day long

**End to end re-run**
- [x] Test day long with multiple in flight queries
- [x] Re-run specialized and tune it
- [x] Re-run scale down and tune it
- [x] Re-run txn scale up and tune it

**Detailed experiments**
- [x] Query routing microexperiment
- [x] Update the end-to-end overhead numbers
- [x] Run time model accuracy under scenarios
  - [x] Adding new table
  - [x] Joining against more tables than it was trained on
  - [x] Predicting over larger data scales
  - [x] Add simple baseline for comparison
- [x] Resource and load scaling models (test accuracy)
- [x] Model test accuracy
- [x] Blueprint search effectiveness
- [x] Blueprint planner sensitivity
