### ISSUE TITLE
Revision progress tracker

### ISSUE THREAD

**Issue by geoffxy** [mitdbg/brad#487]
### New experiments
- [x] Run CH-BenCHmark on some fixed configuration and show BRAD's blueprint planner in action
  - [x] Add support for CH-BenCHmark (#486)
  - [x] Model updates
    - [x] Generate new training data based on the benchmark
    - [x] Update the GNN
      - [x] Implement and run data gathering
      - [x] Fit models
    - [x] Update the transaction models
      - [x] Implement and run data gathering
      - [x] Get to the bottom of the high transaction latency, decide on a path forward
      - [x] Fit models 
    - [x] Update the hardware scaling models
      - [x] Implement and run data gathering
      - [x] Fit models
    - [x] Check in precomputed predictions
  - [x] Tune and select experiment scenario
  - [x] Plot results and add to revision
  - [x] Add TiDB baseline results to the plot
- [x] Scenario with changed SLOs
  - [x] Add ability to change the SLOs while BRAD is running (#489)
  - [x] Tune and select experiment scenario
  - [x] Plot results and add to revision
  - [x] Add TiDB baseline
  - [x] Update BRAD starting instance to improve cost differential obviousness
- [x] Re-run with table movement enabled
  - [x] Scale down
  - [x] Scale up (transactions)
    - Not needed to re-run; there will be no effect since the table placement does not change in the scenario
  - [x] Specialized functionality workload
- [x] Beam search sensitivity experiment

### Writing changes
- [x] Add responses to reviewer comments
  - [x] Write polystore response (R1)
  - [x] Edit the baseline response (R1)
- [x] Writing adjustments
  - [x] Slightly alter introduction to better present the blueprint planning idea (requested by R4)
  - [x] Add short paragraph describing extensibility to additional engines (requested by R4)
- [x] Major writing adjustments
  - [x] Add more detail on the search algorithm
  - [x] Highlight physical plan novelty on the model, hoist this up more into the key ideas section
  - [x] Sprinkle in discussion points throughout the paper (Incorporate every comment into the main paper)

### Nice to haves
- [x] ~~Re-run scale down to have a larger transactional latency SLO buffer~~
